trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && ls -al
    condition: and(succeeded(), eq(variables['agent.os'], 'Darwin'))
    displayName: 'Build (macOS)'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: mkdir dist\\win && cd dist\\win && echo>empty-win.txt && dir
    condition: and(succeeded(), eq(variables['agent.os'], 'Winndows_NT'))
    displayName: 'Build (Windows)'
