jobs:
- job: release_macos
  displayName: 'Release Build (macOS)'
  pool:
    # vmImage: 'macOS-10.13'
    vmImage: 'ubuntu-16.04'
    steps:
    - bash: echo '##vso[task.setvariable variable=Version;isOutput=true]$(Build.BuildNumber)'
      #   condition: eq(variables['Build.SourceBranchName'], 'master')
      #   displayName: 'if master branch Version=1.0.x'
      # - bash: echo '##vso[task.setvariable variable=Version;isOutput=true]$(Build.BuildNumber)-$(Build.SourceBranchName)'
      #   condition: ne(variables['Build.SourceBranchName'], 'master')
      #   displayName: 'if not master branch Version=1.0.x-branch'
      # - bash: echo $(Version)
      #   displayName: 'echo version'
