jobs:
- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: rm -rf dist && mkdir dist && echo `date` > dist/my-release.txt && zip -jr ./dist/my-release.zip ./dist/my-release.txt && echo `date` > dist/my-release2.txt && zip -jr ./dist/my-release2.zip ./dist/my-release2.txt
    displayName: 'Create Release'
  - script: echo $(Release.Tag)
    displayName: 'Create Release'
  - task: GithubRelease@0
    inputs:
      gitHubConnection: kittaakos
      repositoryName: kittaakos/azure-sandbox
      assets:
        dist/my-release.zip
        dist/my-release2.zip
      target: $(Build.SourceVersion)
      action: Edit
      tagSource: auto
      tag: $(Release.Tag)
      assetUploadMode: delete
      isDraft: notIn(variables['Release.IsDraft'], 'false')
      addChangeLog: notIn(variables['Release.AddChangeLog'], 'false')
    condition: and(in(variables['Build.Reason'], 'Manual', 'Schedule'), and(ne(variables['Release.Tag'], ''), startsWith(variabled['Release.Tag'], 'v')))
