jobs:
- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: rm -rf dist && mkdir dist && echo `date` > dist/my-release.txt && zip -jr ./dist/my-release.zip ./dist/my-release.txt
    displayName: 'Create Release'
  - script: echo $(Release.Tag)
    displayName: 'Create Release'
  - task: GithubRelease@0
    inputs:
      gitHubConnection: kittaakos
      repositoryName: kittaakos/azure-sandbox
      assets: dist/my-release.zip
      target: $(Build.SourceVersion)
      action: Edit
      tagSource: auto
      tag: $(Release.Tag)
      assetUploadMode: delete
      isDraft: ne(variables['Release.IsDraft'], false)
      addChangeLog: ne(variables['Release.AddChangeLog'], false)
    condition: and(in(variables['Build.Reason'], 'Manual', 'Schedule'), ne(variables['Release.Tag'], ''))
