pool: hosted ubuntu 1604
variables:
   someVar: true
   otherVar: false
   BR: $(Build.Reason)
steps:
- ${{ if or(ne(variables['someVar'], ''), ne(variables['otherVar'], '')) }}:
   - template: mytemplate.yml
- script: echo hi
- script: echo the BR is $BR