pool: hosted ubuntu 1604
variables:
   someVar: true
steps:
- script: echo someVar is $(someVar)
  displayName: 'Check someVar Script'
- script: 'echo someVar is $(someVar) in a conditional script'
  condition: ne(variables['someVar'], '')
  displayName: 'Conditional Script'
- ${{ if ne(variables['someVar'], '') }}:
   - template: mytemplate.yml
- script: echo hi
  displayName: 'Always Run Script'