trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      export IPADDR=$(ifconfig | grep 'en0' -A3 | tail -n1 | awk '{print $2}')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
  - script: |
      echo The IP address is $IP_ADDR on macOS.

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      Set-Variable -Name IPADDR -Value (Get-NetIPAddress | ?{ $_.AddressFamily -eq "IPv4" -and !($_.IPAddress -match "169") -and !($_.IPaddress -match "127") }).IPAddress
      Write-Host "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
  - script: |
      echo The IP address is %IP_ADDR% on Windows. [CMD.exe]
  - powershell: |
      echo The IP address is $IP_ADDR on Windows. [PowerShell]

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      export IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
      echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
  - script: |
      echo The IP address is $IP_ADDR on Linux.
