trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]$(git rev-parse --short HEAD)'
  - script: echo my variable is $(myVariable)
  - script: mkdir dist/mac && cd dist/mac && echo "on mac" > mac-$(myVariable).txt && ls -al


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]$(git rev-parse --short HEAD)'
  - script: echo my variable is $(myVariable)
  - script: mkdir dist/win && cd dist/win && echo "on windows" > win-$(myVariable).txt && dir


- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]$(git rev-parse --short HEAD)'
  - script: echo my variable is $(myVariable)
  - script: mkdir dist/linux && cd dist/linux && echo "on linux" > linux-$(myVariable).txt && ls -al