trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && ls -al
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/dist/mac/empty-mac.txt
      artifactName: 'empty-mac.txt'
    displayName: 'Publis Build'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: mkdir dist\\win && cd dist\\win && echo>empty-win.txt && dir
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: $(Build.ArtifactStagingDirectory)/dist/win/empty-win.txt
      artifactName: 'empty-win.txt'

# - job: Publish
#   dependsOn:
#   - macOS
#   - Windows
#   condition: succeeded()
#   pool:
#     vmImage: 'Ubuntu 16.04'
#   steps:
#   - task: PublishBuildArtifacts@1
#     displayName: 'Publish end to end test artifact'
#     inputs:
#       pathtoPublish: '$(Build.ArtifactStagingDirectory)/dist'
#       artifactName: dist