trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: mkdir -p dist/mac && cd dist/mac && echo > empty-mac.txt && zip empty-mac.zip empty-mac.txt
    displayName: 'Dummy Build'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/mac/empty-mac.zip
      artifactName: 'empty-mac.zip'
    displayName: 'Publis Build'
