jobs:
- job: release_macos
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
    - template: azure-pipelines-template.yml

- job: release_windows
  displayName: 'Release Build (Linux)'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: azure-pipelines-template.yml

- job: gh_release_linux
  displayName: 'GitHub Release Build (Windows)'
  pool:
    vmImage: 'vs2017-win2016'
  dependsOn:
    - release_macos
    - release_windows
  steps:
    - task: DownloadBuildArtifacts@0
      displayName: Download Release Artifacts
      inputs:
        artifactName: 'folder'
        downloadPath: 'gh-release'
    - task: GithubRelease@0
      inputs:
        gitHubConnection: kittaakos
        repositoryName: kittaakos/azure-sandbox
        assets: |
          gh-release/folder/name-*.zip
          gh-release/folder/name-*.dmg
        target: $(Build.SourceVersion)
        action: Edit
        tagSource: auto
        tag: 'v1.1.1'
        assetUploadMode: delete
        isDraft: true
        addChangeLog: true
      displayName: 'Create GitHub Release'