trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]abc123'
  - script: echo my variable is $(myVariable)


- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]abc123'
  - script: echo my variable is $(myVariable)


- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo '##vso[task.setvariable variable=myVariable]abc123'
  - script: echo my variable is $(myVariable)