jobs:
- job: release_macOS
  displayName: 'Release Build (macOS)'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: rm -rf dist && mkdir dist && echo `date` > dist/my-release.txt && zip -jr ./dist/my-release.zip ./dist/my-release.txt
    displayName: 'Create Release'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: dist/my-release.zip
      artifactName: 'my-release.zip'
    displayName: 'Publish Release'
